/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexBerlekampZassenhausMathlib.SignatureClasses
public import HexLLLMathlib.ShortVector

public section
set_option backward.proofsInPublic true

/-!
BHKS lattice-side objects for the van Hoeij `W ⊆ L'` adequacy: the projected-row spans, the
`0/1` support indicators, the `RecoveredLift` certificate, the Gram-Schmidt
prefix-survivor lemma (Klüners Lemma 1: any lattice vector within the cut
radius lies in the retained prefix span), and the cut-projection producer
`cutProjectionHypotheses_of_shortVectors` that places each true support's
indicator in the executable projected row span.
-/

namespace HexBerlekampZassenhausMathlib

noncomputable section

namespace BHKS


/--
The reduced matrix stored in the BHKS projected-row trace generates the same
integer row lattice as the original BHKS basis.  This carries
`lllNative.shortVectors`'s `.toArray` output back to the certified LLL
lattice-preservation theorem `Hex.lllNative_memLattice_iff`.
-/
theorem traceReducedMatrix_memLattice_iff
    (L : Hex.BhksLatticeBasis) (hrows : 1 ≤ L.factorCount + L.coeffWidth)
    (v : Vector Int (L.factorCount + L.coeffWidth)) :
    Hex.Matrix.memLattice (Hex.bhksProjectedRowsTrace L hrows).reducedMatrix v ↔
      Hex.Matrix.memLattice L.basis v := by
  rw [Hex.bhksProjectedRowsTrace_reducedMatrix_eq]
  exact Hex.lllNative_memLattice_iff L.basis (3 / 4)
    Hex.lll_delta_lower Hex.lll_delta_upper hrows v

/-- The projected integer rows of the executable BHKS cut as a Mathlib matrix. -/
@[expose]
def projectedRowsIntMatrix (L : Hex.BhksProjectedRows) :
    Matrix (Fin L.projectedRows.size) (Fin L.factorCount) ℤ :=
  fun i j => (L.projectedRows.getD i.val #[]).getD j.val 0

/-- The projected rational rows of the executable BHKS cut as a Mathlib matrix. -/
@[expose]
def projectedRowsRatMatrix (L : Hex.BhksProjectedRows) :
    Matrix (Fin L.projectedRows.size) (Fin L.factorCount) ℚ :=
  fun i j => ((L.projectedRows.getD i.val #[]).getD j.val 0 : ℚ)

/--
The integer row span represented by the executable projected BHKS rows.  This
is the proof-facing `L' <= Z^r`.
-/
@[expose]
def projectedRowSpanInt (L : Hex.BhksProjectedRows) :
    Submodule ℤ (Fin L.factorCount → ℤ) :=
  Submodule.span ℤ (Set.range fun i : Fin L.projectedRows.size =>
    Matrix.row (projectedRowsIntMatrix L) i)

/--
The rational row space represented by the same executable projected rows.  This
is the row-space input used by the RREF equivalence-class stage.
-/
@[expose]
def projectedRowSpaceRat (L : Hex.BhksProjectedRows) :
    Submodule ℚ (Fin L.factorCount → ℚ) :=
  Submodule.span ℚ (Set.range fun i : Fin L.projectedRows.size =>
    Matrix.row (projectedRowsRatMatrix L) i)

/-- Cast an integer vector over the lifted-factor indices to a rational vector. -/
@[expose]
def intVectorToRat {r : Nat} (v : Fin r → ℤ) : Fin r → ℚ :=
  fun i => (v i : ℚ)

/-- A `0/1` indicator vector for a support of lifted factor indices. -/
@[expose]
def indicatorVector {r : Nat} (S : Set (Fin r)) : Fin r → ℤ :=
  by
    classical
    exact fun i => if i ∈ S then 1 else 0

/-- The integer lattice `W` generated by the indicator vectors of the true
factor supports.  This is the proof-facing counterpart of the retained
projected row lattice `projectedRowSpanInt`. -/
@[expose]
def trueSupportSpanInt {r : Nat} (trueSupports : Set (Set (Fin r))) :
    Submodule ℤ (Fin r → ℤ) :=
  Submodule.span ℤ
    (Set.range fun S : trueSupports => indicatorVector S.1)

/-- Every true-support indicator is one of the generators of `W`. -/
theorem indicatorVector_mem_trueSupportSpanInt {r : Nat}
    (trueSupports : Set (Set (Fin r))) (S : trueSupports) :
    indicatorVector S.1 ∈ trueSupportSpanInt trueSupports := by
  exact Submodule.subset_span (Set.mem_range_self S)

@[simp, grind =] theorem indicatorVector_apply_mem {r : Nat} (S : Set (Fin r))
    {i : Fin r} (hi : i ∈ S) :
    indicatorVector S i = 1 := by
  simp [indicatorVector, hi]

@[simp, grind =] theorem indicatorVector_apply_not_mem {r : Nat} (S : Set (Fin r))
    {i : Fin r} (hi : i ∉ S) :
    indicatorVector S i = 0 := by
  simp [indicatorVector, hi]

/-- Each coordinate of an indicator vector has squared real norm at most one. -/
theorem indicatorVector_sq_apply_le_one {r : Nat} (S : Set (Fin r)) (i : Fin r) :
    ((((indicatorVector S i : ℤ) : ℝ) ^ 2)) ≤ 1 := by
  classical
  by_cases hi : i ∈ S
  · rw [indicatorVector_apply_mem S hi]
    norm_num
  · rw [indicatorVector_apply_not_mem S hi]
    norm_num

/-- The squared real norm of a `0/1` indicator vector is at most the ambient
dimension. -/
theorem indicatorVector_sq_sum_le_factorCount {r : Nat} (S : Set (Fin r)) :
    (∑ i : Fin r, ((((indicatorVector S i : ℤ) : ℝ) ^ 2))) ≤ (r : ℝ) := by
  calc
    (∑ i : Fin r, ((((indicatorVector S i : ℤ) : ℝ) ^ 2)))
        ≤ ∑ _i : Fin r, (1 : ℝ) := by
          exact Finset.sum_le_sum (fun i _hi => indicatorVector_sq_apply_le_one S i)
    _ = (r : ℝ) := by
          simp

/-- The BHKS cut-radius expression dominates the squared norm of every
true-support indicator vector. -/
theorem indicatorVector_sq_sum_le_bhksCutRadiusSq4
    (L : Hex.BhksLatticeBasis) (S : Set (Fin L.factorCount)) :
    (∑ i : Fin L.factorCount, ((((indicatorVector S i : ℤ) : ℝ) ^ 2))) ≤
      (Hex.bhksCutRadiusSq4 L : ℝ) := by
  have hnorm := indicatorVector_sq_sum_le_factorCount S
  have hfactor_le_cut :
      (L.factorCount : ℝ) ≤ (Hex.bhksCutRadiusSq4 L : ℝ) := by
    unfold Hex.bhksCutRadiusSq4
    have hnat :
        L.factorCount ≤ 4 * L.factorCount + L.coeffWidth * L.factorCount * L.factorCount := by
      exact Nat.le_trans (Nat.le_mul_of_pos_left L.factorCount (by decide : 0 < 4))
        (Nat.le_add_right _ _)
    exact_mod_cast hnat
  exact hnorm.trans hfactor_le_cut

/-- Projected-row form of `indicatorVector_sq_sum_le_bhksCutRadiusSq4`, stated
against the cut-radius field stored by the executable Gram-Schmidt cut output. -/
theorem indicatorVector_sq_sum_le_projectedRows_cutRadiusSq4
    (L : Hex.BhksLatticeBasis)
    (hrows : 1 ≤ L.factorCount + L.coeffWidth)
    (S : Set (Fin (Hex.bhksProjectedRows L hrows).factorCount)) :
    (∑ i : Fin (Hex.bhksProjectedRows L hrows).factorCount,
        ((((indicatorVector S i : ℤ) : ℝ) ^ 2))) ≤
      ((Hex.bhksProjectedRows L hrows).cutRadiusSq4 : ℝ) := by
  exact indicatorVector_sq_sum_le_bhksCutRadiusSq4 L S


/-- A support of lifted local-factor indices for a BHKS lattice basis. -/
abbrev LiftedFactorSupport (L : Hex.BhksLatticeBasis) :=
  Set (Fin L.factorCount)

/-- The `0/1` indicator vector attached to a lifted-factor support. -/
def liftedFactorIndicator (L : Hex.BhksLatticeBasis) (S : LiftedFactorSupport L) :
    Fin L.factorCount → ℤ :=
  indicatorVector S

/--
Product of the lifted factors selected by a support, using the factor order
stored in the BHKS lattice basis.  The definition indexes by `factorCount`
rather than the raw array size so it remains well-typed for abstract
`BhksLatticeBasis` values; `TrueFactorLift.basis_eq` ties these together for
the executable basis.
-/
@[expose]
def supportProduct (L : Hex.BhksLatticeBasis) (S : LiftedFactorSupport L) :
    Hex.ZPoly :=
  by
    classical
    exact Array.polyProduct <|
      (((List.finRange L.factorCount).filter fun i => decide (i ∈ S)).map
        fun i => L.liftedFactors.getD i.val 1).toArray

/--
Sum of the per-selected-factor executable CLD quotients, taken over the same
factor order as `supportProduct`.  Its `j`-th coefficient is the pre-`psiCut`,
pre-indicator column-`j` entry of the true-factor CLD vector; the centering
(`psiCut`) and indicator weighting are layered on top by the tight-column work
described later in this module.
-/
@[expose]
def supportCldSum (L : Hex.BhksLatticeBasis) (S : LiftedFactorSupport L)
    (f : Hex.ZPoly) (p a : Nat) : Hex.ZPoly :=
  by
    classical
    exact
      (((List.finRange L.factorCount).filter fun i => decide (i ∈ S)).map
        fun i => Hex.cldQuotientMod f (L.liftedFactors.getD i.val 1) p a).sum


/--
Proof-facing package for a true factor in the direct Hensel coordinate.

The selected monic local product represents the integer factor only up to the
two constant scales inherent in the direct coordinate:

* `leadingCoeff f` converts the monic Hensel target back to the input
  coordinate;
* `factorScale` is the leading coefficient of the complementary integer
  factor.

`scaledProduct_congr` records precisely that proportionality modulo the Hensel
modulus.  `inputScale_coprime` says the input leading coefficient is a unit
there, which is the exact scalar cancelled after the monic support product is
cancelled in logarithmic derivatives.  There is no dilation-coordinate recovery
equation in this interface.
-/
structure RecoveredLift
    (L : Hex.BhksLatticeBasis) (S : LiftedFactorSupport L) where
  /-- The integer polynomial from which the lattice was constructed. -/
  f : Hex.ZPoly
  /-- The prime underlying the Hensel lift. -/
  p : Nat
  /-- The exponent in the lift modulus `p ^ a`. -/
  a : Nat
  /-- The local factors used to construct the lattice. -/
  liftedFactors : Array Hex.ZPoly
  /-- The abstract lattice is the lattice constructed from these data. -/
  basis_eq : L = Hex.bhksLatticeBasis f p a liftedFactors
  /-- The integer factor represented by the support. -/
  factor : Hex.ZPoly
  /-- The complementary integer factor. -/
  cofactor : Hex.ZPoly
  /-- The factor and cofactor multiply to the input polynomial. -/
  factor_mul : factor * cofactor = f
  /-- The scalar relating the support product to the represented factor. -/
  factorScale : Int
  /-- The input leading coefficient is invertible modulo the lift modulus. -/
  inputScale_coprime :
    Int.gcd (Hex.DensePoly.leadingCoeff f) (Int.ofNat (p ^ a)) = 1
  /-- The scaled support product agrees with the scaled factor modulo the lift modulus. -/
  scaledProduct_congr :
    Hex.ZPoly.congr
      (Hex.DensePoly.scale (Hex.DensePoly.leadingCoeff f) (supportProduct L S))
      (Hex.DensePoly.scale factorScale factor)
      (p ^ a)

/-- A left fold accumulating `g` over a list equals the running accumulator plus
the sum of the mapped list; the start-from-`acc` form used to read a fold-sum off
at `acc = 0`. -/
private theorem foldl_add_eq_acc_add_listSum {M : Type*} [AddCommMonoid M]
    {α : Type*} (l : List α) (g : α → M) (acc : M) :
    l.foldl (fun acc i => acc + g i) acc = acc + (l.map g).sum := by
  induction l generalizing acc with
  | nil => simp
  | cons x xs ih =>
      simp only [List.foldl_cons, List.map_cons, List.sum_cons]
      rw [ih, add_assoc]

/-- A fold-sum over `List.finRange n` equals the finite sum over `Fin n`. -/
theorem finRange_foldl_add_eq_sum {M : Type*} [AddCommMonoid M] {n : Nat}
    (g : Fin n → M) :
    (List.finRange n).foldl (fun acc i => acc + g i) 0 = ∑ i, g i := by
  rw [foldl_add_eq_acc_add_listSum, zero_add, Fin.sum_univ_def]

/-- The entry of a row combination at column `k` is the explicit finite sum, over
the row index, of the column-`k` matrix entries weighted by the coefficients. -/
theorem vecMul_getElem_eq_sum {n m : Nat}
    (M : Hex.Matrix ℤ n m) (c : Vector ℤ n) (k : Fin m) :
    (Hex.Matrix.vecMul c M)[k] = ∑ i : Fin n, M[i][k] * c[i] := by
  show (Hex.Matrix.transpose M * c)[k] = _
  rw [Hex.Matrix.getElem_mulVec]
  unfold Vector.dotProduct
  rw [finRange_foldl_add_eq_sum
    (g := fun i : Fin n => (Hex.Matrix.row (Hex.Matrix.transpose M) k)[i] * c[i])]
  refine Finset.sum_congr rfl ?_
  intro i _
  rw [Hex.Matrix.getElem_row, Hex.Matrix.getElem_transpose]

/-- Every matrix row belongs to the integer lattice generated by the matrix. -/
theorem matrixRow_memLattice {n m : Nat}
    (M : Hex.Matrix ℤ n m) (i : Fin n) :
    Hex.Matrix.memLattice M (Hex.Matrix.row M i) := by
  let c : Vector ℤ n := Vector.ofFn fun j => if j = i then 1 else 0
  refine ⟨c, ?_⟩
  apply Vector.ext
  intro k hk
  have hentry := vecMul_getElem_eq_sum M c ⟨k, hk⟩
  rw [Finset.sum_eq_single i] at hentry
  · change (Hex.Matrix.vecMul c M)[k] = (Hex.Matrix.getRow M i)[k]
    simpa [c] using hentry
  · intro j _ hji
    simp [c, hji]
  · simp


/--
Certificate for an arbitrary short BHKS lattice vector whose first block is the
indicator of a true lifted-factor support.

This is the projection surface needed by period-adjusted BHKS arguments: the
short vector need not be the zero-period-row `trueFactorCLDVector`; it only has
to lie in the BHKS row lattice, project to the support indicator, and satisfy
the tight cut radius bound.
-/
structure SupportShortVectorData
    (L : Hex.BhksLatticeBasis) (S : LiftedFactorSupport L) where
  /-- A short vector in the row lattice. -/
  vector : Vector ℤ (L.factorCount + L.coeffWidth)
  /-- The vector is an integer combination of the lattice rows. -/
  memLattice : Hex.Matrix.memLattice L.basis vector
  /-- The first coordinates form the indicator vector of `S`. -/
  project_eq :
    ∀ i : Fin L.factorCount,
      vector[(⟨i.val, Nat.lt_add_right L.coeffWidth i.isLt⟩ :
        Fin (L.factorCount + L.coeffWidth))] = indicatorVector S i
  /-- Four times the squared Euclidean norm is within the cut radius. -/
  four_mul_sq_norm_le :
    4 * (∑ i : Fin (L.factorCount + L.coeffWidth),
      ((((vector[i] : ℤ) : ℝ) ^ 2))) ≤ (Hex.bhksCutRadiusSq4 L : ℝ)

/-- Every coordinate of a support short vector is bounded by the BHKS cut
radius.  This deliberately uses the radius itself, rather than its square
root, so that the later integral coefficient estimate stays elementary. -/
theorem SupportShortVectorData.coord_natAbs_le
    {L : Hex.BhksLatticeBasis} {S : LiftedFactorSupport L}
    (D : SupportShortVectorData L S)
    (x : Fin (L.factorCount + L.coeffWidth)) :
    D.vector[x].natAbs ≤ Hex.bhksCutRadiusSq4 L := by
  have hcoord :
      ((((D.vector[x] : ℤ) : ℝ) ^ 2)) ≤
        ∑ i : Fin (L.factorCount + L.coeffWidth),
          ((((D.vector[i] : ℤ) : ℝ) ^ 2)) := by
    exact Finset.single_le_sum (fun i _ => sq_nonneg (((D.vector[i] : ℤ) : ℝ)))
      (Finset.mem_univ x)
  have hsum_nonneg :
      0 ≤ ∑ i : Fin (L.factorCount + L.coeffWidth),
        ((((D.vector[i] : ℤ) : ℝ) ^ 2)) :=
    Finset.sum_nonneg fun i _ => sq_nonneg (((D.vector[i] : ℤ) : ℝ))
  have hsum :
      (∑ i : Fin (L.factorCount + L.coeffWidth),
        ((((D.vector[i] : ℤ) : ℝ) ^ 2))) ≤
          (Hex.bhksCutRadiusSq4 L : ℝ) := by
    have hR : 0 ≤ (Hex.bhksCutRadiusSq4 L : ℝ) := Nat.cast_nonneg _
    linarith [D.four_mul_sq_norm_le]
  have habs_sq : D.vector[x].natAbs ≤ (D.vector[x] : ℤ) ^ 2 :=
    Int.natAbs_le_self_sq D.vector[x]
  have habs_sq_real :
      (D.vector[x].natAbs : ℝ) ≤ (((D.vector[x] : ℤ) : ℝ) ^ 2) := by
    have hcast :
        (((D.vector[x].natAbs : ℤ) : ℝ)) ≤
          ((((D.vector[x] : ℤ) ^ 2 : ℤ) : ℝ)) :=
      Int.cast_le.mpr habs_sq
    simpa using hcast
  exact_mod_cast habs_sq_real.trans (hcoord.trans hsum)


/--
The BHKS block-form predicate: `L.basis` is the all-coefficients CLD row basis
`[ I | A_tilde; 0 | diag ]` built by `bhksLatticeEntry` from `L`'s own data.
This holds definitionally for `Hex.bhksLatticeBasis` (see
`bhksLatticeBasis_blockForm`) and is the only fact the canonical coordinate
producers need about the basis.
-/
@[expose]
def BhksBlockForm (L : Hex.BhksLatticeBasis) : Prop :=
  L.basis =
    Hex.Matrix.ofFn
      (Hex.bhksLatticeEntry L.factorCount L.coeffWidth L.p L.precision
        L.cutThresholds L.cldRows)

/-- The executable `bhksLatticeBasis` has block form by construction. -/
theorem bhksLatticeBasis_blockForm
    (f : Hex.ZPoly) (p a : Nat) (liftedFactors : Array Hex.ZPoly) :
    BhksBlockForm (Hex.bhksLatticeBasis f p a liftedFactors) := rfl

/-- The first block of a row combination of a BHKS block-form basis is exactly
the first block of its row-coefficient vector. -/
theorem vecMul_first_of_blockForm
    (L : Hex.BhksLatticeBasis) (hL : BhksBlockForm L)
    (c : Vector ℤ (L.factorCount + L.coeffWidth)) (i : Fin L.factorCount) :
    (Hex.Matrix.vecMul c L.basis)[Fin.castAdd L.coeffWidth i] =
      c[Fin.castAdd L.coeffWidth i] := by
  rw [vecMul_getElem_eq_sum, Fin.sum_univ_add]
  have hentry : ∀ x : Fin (L.factorCount + L.coeffWidth),
      L.basis[x][Fin.castAdd L.coeffWidth i] =
        Hex.bhksLatticeEntry L.factorCount L.coeffWidth L.p L.precision
          L.cutThresholds L.cldRows x (Fin.castAdd L.coeffWidth i) := by
    intro x
    rw [hL, Hex.Matrix.getElem_ofFn]
  have hsnd : (∑ j : Fin L.coeffWidth,
      L.basis[Fin.natAdd L.factorCount j][Fin.castAdd L.coeffWidth i] *
        c[Fin.natAdd L.factorCount j]) = 0 := by
    apply Finset.sum_eq_zero
    intro j _
    rw [hentry]
    unfold Hex.bhksLatticeEntry
    rw [dif_neg (by simp only [Fin.val_natAdd]; omega),
      dif_pos (by simp only [Fin.val_castAdd]; exact i.isLt), zero_mul]
  rw [hsnd, add_zero]
  rw [Finset.sum_eq_single i]
  · rw [hentry]
    unfold Hex.bhksLatticeEntry
    simp only [Fin.val_castAdd, i.isLt, ↓reduceDIte, ↓reduceIte, one_mul]
  · intro i' _ hne
    rw [hentry]
    unfold Hex.bhksLatticeEntry
    rw [dif_pos (by simp only [Fin.val_castAdd]; exact i'.isLt),
      dif_pos (by simp only [Fin.val_castAdd]; exact i.isLt),
      if_neg (by
        intro hval
        exact hne (Fin.ext hval))]
    exact zero_mul _
  · intro h
    exact absurd (Finset.mem_univ i) h

/-- The tail block of a row combination of a BHKS block-form basis is its CLD
column combination plus the corresponding diagonal-period contribution. -/
theorem vecMul_tail_of_blockForm
    (L : Hex.BhksLatticeBasis) (hL : BhksBlockForm L)
    (c : Vector ℤ (L.factorCount + L.coeffWidth)) (j : Fin L.coeffWidth) :
    (Hex.Matrix.vecMul c L.basis)[Fin.natAdd L.factorCount j] =
      (∑ i : Fin L.factorCount,
        c[Fin.castAdd L.coeffWidth i] *
          (L.cldRows.getD i.val #[]).getD j.val 0) +
      Int.ofNat (L.p ^ (L.precision - L.cutThresholds.getD j.val 0)) *
        c[Fin.natAdd L.factorCount j] := by
  rw [vecMul_getElem_eq_sum, Fin.sum_univ_add]
  have hentry : ∀ x : Fin (L.factorCount + L.coeffWidth),
      L.basis[x][Fin.natAdd L.factorCount j] =
        Hex.bhksLatticeEntry L.factorCount L.coeffWidth L.p L.precision
          L.cutThresholds L.cldRows x (Fin.natAdd L.factorCount j) := by
    intro x
    rw [hL, Hex.Matrix.getElem_ofFn]
  have hfst : (∑ i : Fin L.factorCount,
      L.basis[Fin.castAdd L.coeffWidth i][Fin.natAdd L.factorCount j] *
        c[Fin.castAdd L.coeffWidth i]) =
      ∑ i : Fin L.factorCount,
        c[Fin.castAdd L.coeffWidth i] *
          (L.cldRows.getD i.val #[]).getD j.val 0 := by
    refine Finset.sum_congr rfl ?_
    intro i _
    rw [hentry]
    unfold Hex.bhksLatticeEntry
    rw [dif_pos (by simp only [Fin.val_castAdd]; exact i.isLt),
      dif_neg (by simp only [Fin.val_natAdd]; omega)]
    simp only [Fin.val_castAdd, Fin.val_natAdd, Nat.add_sub_cancel_left]
    ring
  have hsnd : (∑ j' : Fin L.coeffWidth,
      L.basis[Fin.natAdd L.factorCount j'][Fin.natAdd L.factorCount j] *
        c[Fin.natAdd L.factorCount j']) =
      Int.ofNat (L.p ^ (L.precision - L.cutThresholds.getD j.val 0)) *
        c[Fin.natAdd L.factorCount j] := by
    rw [Finset.sum_eq_single j]
    · rw [hentry]
      rw [Hex.bhksLatticeEntry_bottomRight_diag
        L.factorCount L.coeffWidth L.p L.precision L.cutThresholds L.cldRows
        (Fin.natAdd L.factorCount j) (by simp)]
      simp only [Fin.val_natAdd, Nat.add_sub_cancel_left]
    · intro j' _ hne
      rw [hentry]
      unfold Hex.bhksLatticeEntry
      rw [dif_neg (by simp only [Fin.val_natAdd]; omega),
        dif_neg (by simp only [Fin.val_natAdd]; omega)]
      simp only [Fin.val_natAdd, Nat.add_sub_cancel_left]
      rw [if_neg (by
        intro hval
        exact hne (Fin.ext hval.symm))]
      exact zero_mul _
    · intro h
      exact absurd (Finset.mem_univ j) h
  rw [hfst, hsnd]


namespace RecoveredLift

/-- A recovered lift package supplies the BHKS block form used by coordinate
and norm-bound reducers. -/
theorem blockForm
    {L : Hex.BhksLatticeBasis} {S : LiftedFactorSupport L}
    (D : RecoveredLift L S) :
    BhksBlockForm L := by
  rcases D with ⟨f, p, a, liftedFactors, basis_eq, factor, cofactor, factor_mul,
    factorScale, inputScale_coprime, scaledProduct_congr⟩
  cases basis_eq
  exact bhksLatticeBasis_blockForm f p a liftedFactors

/-- The packaged basis carries exactly the lifted-factor array used to build
the executable BHKS lattice. -/
theorem liftedFactors_eq
    {L : Hex.BhksLatticeBasis} {S : LiftedFactorSupport L}
    (D : RecoveredLift L S) :
    L.liftedFactors = D.liftedFactors := by
  rcases D with ⟨f, p, a, liftedFactors, basis_eq, factor, cofactor, factor_mul,
    factorScale, inputScale_coprime, scaledProduct_congr⟩
  cases basis_eq
  rfl

/-- The packaged basis carries exactly the cut thresholds computed from the
input polynomial and prime. -/
theorem cutThresholds_eq
    {L : Hex.BhksLatticeBasis} {S : LiftedFactorSupport L}
    (D : RecoveredLift L S) :
    L.cutThresholds = Hex.bhksCutThresholds D.f D.p := by
  rcases D with ⟨f, p, a, liftedFactors, basis_eq, factor, cofactor, factor_mul,
    factorScale, inputScale_coprime, scaledProduct_congr⟩
  cases basis_eq
  rfl

/-- The packaged basis carries exactly the CLD rows computed from the concrete
lifted factors. -/
theorem cldRows_eq
    {L : Hex.BhksLatticeBasis} {S : LiftedFactorSupport L}
    (D : RecoveredLift L S) :
    L.cldRows = D.liftedFactors.map (fun g => Hex.cldCoeffs D.f D.p D.a g) := by
  rcases D with ⟨f, p, a, liftedFactors, basis_eq, factor, cofactor, factor_mul,
    factorScale, inputScale_coprime, scaledProduct_congr⟩
  cases basis_eq
  rfl

/-- The packaged basis factor count is exactly the concrete lifted-factor
array size. -/
theorem factorCount_eq
    {L : Hex.BhksLatticeBasis} {S : LiftedFactorSupport L}
    (D : RecoveredLift L S) :
    L.factorCount = D.liftedFactors.size := by
  rcases D with ⟨f, p, a, liftedFactors, basis_eq, factor, cofactor, factor_mul,
    factorScale, inputScale_coprime, scaledProduct_congr⟩
  cases basis_eq
  rfl

/-- The packaged basis coefficient width is exactly the input polynomial degree
used by the executable CLD rows. -/
theorem coeffWidth_eq
    {L : Hex.BhksLatticeBasis} {S : LiftedFactorSupport L}
    (D : RecoveredLift L S) :
    L.coeffWidth = D.f.degree?.getD 0 := by
  rcases D with ⟨f, p, a, liftedFactors, basis_eq, factor, cofactor, factor_mul,
    factorScale, inputScale_coprime, scaledProduct_congr⟩
  cases basis_eq
  rfl

/-- The packaged basis modulus base is exactly the recovered lift's prime. -/
theorem p_eq
    {L : Hex.BhksLatticeBasis} {S : LiftedFactorSupport L}
    (D : RecoveredLift L S) :
    L.p = D.p := by
  rcases D with ⟨f, p, a, liftedFactors, basis_eq, factor, cofactor, factor_mul,
    factorScale, inputScale_coprime, scaledProduct_congr⟩
  cases basis_eq
  rfl

/-- The packaged basis precision is exactly the recovered lift's Hensel
precision. -/
theorem precision_eq
    {L : Hex.BhksLatticeBasis} {S : LiftedFactorSupport L}
    (D : RecoveredLift L S) :
    L.precision = D.a := by
  rcases D with ⟨f, p, a, liftedFactors, basis_eq, factor, cofactor, factor_mul,
    factorScale, inputScale_coprime, scaledProduct_congr⟩
  cases basis_eq
  rfl

end RecoveredLift

/-- Two supports are equivalent when every projected row is constant across them. -/
@[expose]
def supportEquivalent {r : Nat} (trueSupports : Set (Set (Fin r)))
    (j k : Fin r) : Prop :=
  ∀ S ∈ trueSupports, (j ∈ S ↔ k ∈ S)

/-- Nat-indexed form of `supportEquivalent`, convenient for filtering
`List.range r` while retaining proof irrelevance for the bounds. -/
@[expose]
def supportEquivalentAt {r : Nat} (trueSupports : Set (Set (Fin r)))
    (j k : Nat) : Prop :=
  ∃ (hj : j < r) (hk : k < r),
    supportEquivalent trueSupports ⟨j, hj⟩ ⟨k, hk⟩

/-- The natural-index and finite-index forms of support equivalence agree in range. -/
theorem supportEquivalentAt_iff {r : Nat}
    (trueSupports : Set (Set (Fin r))) {j k : Nat}
    (hj : j < r) (hk : k < r) :
    supportEquivalentAt trueSupports j k ↔
      supportEquivalent trueSupports ⟨j, hj⟩ ⟨k, hk⟩ := by
  constructor
  · intro h
    rcases h with ⟨hj', hk', h⟩
    simpa using h
  · intro h
    exact ⟨hj, hk, h⟩

/-- Support equivalence is reflexive on in-range indices. -/
theorem supportEquivalentAt_refl {r : Nat}
    (trueSupports : Set (Set (Fin r))) {j : Nat} (hj : j < r) :
    supportEquivalentAt trueSupports j j := by
  exact ⟨hj, hj, by intro S hS; simp⟩

/-- Support equivalence is symmetric. -/
theorem supportEquivalentAt_symm {r : Nat}
    (trueSupports : Set (Set (Fin r))) {j k : Nat}
    (h : supportEquivalentAt trueSupports j k) :
    supportEquivalentAt trueSupports k j := by
  rcases h with ⟨hj, hk, h⟩
  exact ⟨hk, hj, by intro S hS; exact (h S hS).symm⟩

/-- Support equivalence is transitive. -/
theorem supportEquivalentAt_trans {r : Nat}
    (trueSupports : Set (Set (Fin r))) {i j k : Nat}
    (hij : supportEquivalentAt trueSupports i j)
    (hjk : supportEquivalentAt trueSupports j k) :
    supportEquivalentAt trueSupports i k := by
  rcases hij with ⟨hi, hj, hij⟩
  rcases hjk with ⟨hj', hk, hjk⟩
  exact ⟨hi, hk, by intro S hS; exact (hij S hS).trans (hjk S hS)⟩

/-- Minimum representatives of support-equivalence classes, emitted in
ascending column order. -/
@[expose]
def supportRepresentativeColumns {r : Nat}
    (trueSupports : Set (Set (Fin r))) : List Nat :=
  by
    classical
    exact (List.range r).filter
      (fun j =>
        ((List.range j).filter
          (fun k => decide (supportEquivalentAt trueSupports k j))).isEmpty)

/-- The support-equivalence class represented by `rep`, listed in ascending
column order. -/
@[expose]
def supportClassMembers {r : Nat}
    (trueSupports : Set (Set (Fin r))) (rep : Nat) : List Nat :=
  by
    classical
    exact (List.range r).filter
      (fun j => decide (supportEquivalentAt trueSupports j rep))

/-- Canonical partition of columns by true-support membership signatures. -/
@[expose]
def supportPartitionByMinColumn {r : Nat}
    (trueSupports : Set (Set (Fin r))) : List (List Nat) :=
  (supportRepresentativeColumns trueSupports).map
    (fun rep => supportClassMembers trueSupports rep)

/-- The executable indicator-array shape for a finite Nat-indexed class. -/
@[expose]
def classIndicatorArray (r : Nat) (members : List Nat) : Array Int :=
  ((List.range r).map (fun i => if i ∈ members then (1 : Int) else 0)).toArray

@[simp, grind =] theorem classIndicatorArray_size (r : Nat) (members : List Nat) :
    (classIndicatorArray r members).size = r := by
  unfold classIndicatorArray
  simp

/-- Entries of a class indicator are one exactly at in-range class members. -/
theorem classIndicatorArray_getD
    (r : Nat) (members : List Nat) (i : Nat) :
    (classIndicatorArray r members).getD i 0 =
      if i < r ∧ i ∈ members then 1 else 0 := by
  unfold classIndicatorArray
  by_cases hi : i < r
  · simp [Array.getD, hi]
  · have hsize :
        ((List.range r).map (fun i => if i ∈ members then (1 : Int) else 0)).length = r := by
      simp
    simp [Array.getD, hi, hsize]

/-- Every entry of a class indicator is zero or one. -/
theorem classIndicatorArray_bits (r : Nat) (members : List Nat) :
    ∀ i, i < (classIndicatorArray r members).size →
      (classIndicatorArray r members).getD i 0 = 0 ∨
        (classIndicatorArray r members).getD i 0 = 1 := by
  intro i hi
  rw [classIndicatorArray_size] at hi
  rw [classIndicatorArray_getD]
  by_cases hmem : i ∈ members
  · simp [hi, hmem]
  · simp [hi, hmem]

/-- Every in-range class member has indicator entry one. -/
theorem classIndicatorArray_has_one_of_mem
    (r : Nat) (members : List Nat) {i : Nat}
    (hi : i < r) (hmem : i ∈ members) :
    (classIndicatorArray r members).getD i 0 = 1 := by
  rw [classIndicatorArray_getD]
  simp [hi, hmem]


/-- Support-class representatives are precisely the least indices in their classes. -/
theorem mem_supportRepresentativeColumns_iff {r : Nat}
    (trueSupports : Set (Set (Fin r))) (rep : Nat) :
    rep ∈ supportRepresentativeColumns trueSupports ↔
      rep < r ∧
        ∀ k, k < rep → ¬ supportEquivalentAt trueSupports k rep := by
  classical
  unfold supportRepresentativeColumns
  rw [List.mem_filter]
  simp only [List.mem_range, List.isEmpty_iff]
  constructor
  · rintro ⟨hlt, hfilter⟩
    refine ⟨hlt, ?_⟩
    intro k hk heq
    have : k ∈ (List.range rep).filter
        (fun k => decide (supportEquivalentAt trueSupports k rep)) := by
      rw [List.mem_filter]
      exact ⟨List.mem_range.mpr hk, by simpa using heq⟩
    rw [hfilter] at this
    exact List.not_mem_nil this
  · rintro ⟨hlt, hfresh⟩
    refine ⟨hlt, ?_⟩
    apply List.eq_nil_iff_forall_not_mem.mpr
    intro k hk
    rw [List.mem_filter] at hk
    exact hfresh k (List.mem_range.mp hk.1) (by simpa using hk.2)

/-- Every support-class representative is a valid column index. -/
theorem supportRepresentativeColumns_lt {r : Nat}
    (trueSupports : Set (Set (Fin r))) {rep : Nat}
    (hrep : rep ∈ supportRepresentativeColumns trueSupports) : rep < r :=
  ((mem_supportRepresentativeColumns_iff trueSupports rep).mp hrep).1

/-- No earlier column is support-equivalent to a representative. -/
theorem supportRepresentativeColumns_min {r : Nat}
    (trueSupports : Set (Set (Fin r))) {rep : Nat}
    (hrep : rep ∈ supportRepresentativeColumns trueSupports) :
    ∀ k, k < rep → ¬ supportEquivalentAt trueSupports k rep :=
  ((mem_supportRepresentativeColumns_iff trueSupports rep).mp hrep).2

/-- A column belongs to a representative's class exactly when it is equivalent and in range. -/
theorem mem_supportClassMembers_iff {r : Nat}
    (trueSupports : Set (Set (Fin r))) (rep j : Nat) :
    j ∈ supportClassMembers trueSupports rep ↔
      j < r ∧ supportEquivalentAt trueSupports j rep := by
  classical
  unfold supportClassMembers
  rw [List.mem_filter]
  simp [List.mem_range]

/-- Every support-class representative belongs to its own class. -/
theorem supportClassMembers_rep_mem {r : Nat}
    (trueSupports : Set (Set (Fin r))) {rep : Nat}
    (hrep : rep ∈ supportRepresentativeColumns trueSupports) :
    rep ∈ supportClassMembers trueSupports rep := by
  rw [mem_supportClassMembers_iff]
  exact ⟨supportRepresentativeColumns_lt trueSupports hrep,
    supportEquivalentAt_refl trueSupports
      (supportRepresentativeColumns_lt trueSupports hrep)⟩

theorem supportClassMembers_mem_iff_fin {r : Nat}
    (trueSupports : Set (Set (Fin r))) {rep j : Nat}
    (hj : j < r) (hrep : rep < r) :
    j ∈ supportClassMembers trueSupports rep ↔
      supportEquivalent trueSupports ⟨j, hj⟩ ⟨rep, hrep⟩ := by
  rw [mem_supportClassMembers_iff, supportEquivalentAt_iff trueSupports hj hrep]
  simp [hj]


private theorem foldl_cut_ge_of_bound {N : Nat} (g : Fin N → Bool) (bound : Nat) :
    ∀ (l : List (Fin N)) (init : Nat),
      bound ≤ init → (∀ i ∈ l, bound ≤ i.val + 1) →
      bound ≤ l.foldl (fun acc i => if g i then i.val + 1 else acc) init := by
  intro l
  induction l with
  | nil => intro init hinit _; simpa using hinit
  | cons a tl ih =>
      intro init hinit hbnd
      apply ih
      · by_cases hga : g a
        · simp only [hga, if_true]; exact hbnd a (by simp)
        · simp only [hga, Bool.false_eq_true, if_false]; exact hinit
      · intro i hi; exact hbnd i (List.mem_cons_of_mem a hi)

/-- The cut fold over a strictly increasing index list reaches at least
`k.val + 1` once a passing index `k` has been processed. -/
private theorem foldl_cut_ge {N : Nat} (g : Fin N → Bool) (k : Fin N) :
    ∀ (l : List (Fin N)) (init : Nat),
      l.Pairwise (· < ·) → k ∈ l → g k = true →
      k.val + 1 ≤ l.foldl (fun acc i => if g i then i.val + 1 else acc) init := by
  intro l
  induction l with
  | nil => intro init _ hk _; simp at hk
  | cons a tl ih =>
      intro init hpw hk hgk
      rw [List.pairwise_cons] at hpw
      obtain ⟨hahead, htl⟩ := hpw
      rw [List.foldl_cons]
      rcases List.mem_cons.mp hk with rfl | hktl
      · have hstep : (if g k then k.val + 1 else init) = k.val + 1 := by simp [hgk]
        rw [hstep]
        refine foldl_cut_ge_of_bound g (k.val + 1) tl (k.val + 1) (le_refl _) ?_
        intro i hi
        have hlt : k.val < i.val := hahead i hi
        omega
      · exact ih _ htl hktl hgk

/-- If a cut fold ends above `j`, either its initial accumulator was already
above `j` or some passing list entry has index at least `j`. -/
private theorem exists_cut_of_lt_foldl {N : Nat} (g : Fin N → Bool) (j : Nat) :
    ∀ (l : List (Fin N)) (init : Nat),
      j < l.foldl (fun acc i => if g i then i.val + 1 else acc) init →
      j < init ∨ ∃ k ∈ l, j ≤ k.val ∧ g k = true := by
  intro l
  induction l with
  | nil =>
      intro init h
      exact Or.inl h
  | cons a tl ih =>
      intro init h
      rw [List.foldl_cons] at h
      rcases ih (if g a then a.val + 1 else init) h with hstep | ⟨k, hk, hjk, hgk⟩
      · by_cases hga : g a = true
        · right
          refine ⟨a, by simp, ?_, hga⟩
          simp only [hga, if_true] at hstep
          omega
        · left
          have hgaf : g a = false := Bool.eq_false_of_not_eq_true hga
          simpa [hgaf] using hstep
      · right
        exact ⟨k, List.mem_cons_of_mem a hk, hjk, hgk⟩

/-- Every retained-prefix index is at or before some Gram--Schmidt index that
actually passes the executable cut.  This is the converse direction needed to
control the norms of rows kept only because a later row passes. -/
theorem exists_passing_index_of_lt_prefixCount
    (L : Hex.BhksLatticeBasis)
    (reduced : Hex.Matrix Int (L.factorCount + L.coeffWidth)
        (L.factorCount + L.coeffWidth))
    (j : Fin (L.factorCount + L.coeffWidth))
    (hj : j.val < Hex.bhksCutPrefixCount L reduced) :
    ∃ k : Fin (L.factorCount + L.coeffWidth),
      j.val ≤ k.val ∧
        Hex.bhksWithinGramSchmidtCut L
          (Hex.GramSchmidt.Int.gramDetVec reduced) k = true := by
  unfold Hex.bhksCutPrefixCount at hj
  rcases exists_cut_of_lt_foldl
      (fun i => Hex.bhksWithinGramSchmidtCut L
        (Hex.GramSchmidt.Int.gramDetVec reduced) i)
      j.val (List.finRange _) 0 hj with hzero | ⟨k, _hk, hjk, hpass⟩
  · omega
  · exact ⟨k, hjk, hpass⟩

/-- A Gram-Schmidt index that passes the executable cut test lies strictly below
the retained prefix length `bhksCutPrefixCount`, so its row is kept. -/
theorem bhksWithinGramSchmidtCut_lt_prefixCount
    (L : Hex.BhksLatticeBasis)
    (reduced : Hex.Matrix Int (L.factorCount + L.coeffWidth)
        (L.factorCount + L.coeffWidth))
    (k : Fin (L.factorCount + L.coeffWidth))
    (hk : Hex.bhksWithinGramSchmidtCut L
        (Hex.GramSchmidt.Int.gramDetVec reduced) k = true) :
    k.val < Hex.bhksCutPrefixCount L reduced := by
  unfold Hex.bhksCutPrefixCount
  exact foldl_cut_ge
    (fun i => Hex.bhksWithinGramSchmidtCut L (Hex.GramSchmidt.Int.gramDetVec reduced) i)
    k (List.finRange _) 0 (List.pairwise_lt_finRange _) (List.mem_finRange k) hk

/-- The executable cut test passes at index `i` once the stored leading
Gram determinant at `i` is nonzero and the radius inequality on the consecutive
determinant ratio holds. -/
theorem bhksWithinGramSchmidtCut_eq_true_of_le
    (L : Hex.BhksLatticeBasis)
    (dets : Vector Nat (L.factorCount + L.coeffWidth + 1))
    (i : Fin (L.factorCount + L.coeffWidth))
    (hne : dets.get ⟨i.val, by omega⟩ ≠ 0)
    (hle : 4 * ((dets.get ⟨i.val + 1, by omega⟩ : ℚ) /
        (dets.get ⟨i.val, by omega⟩ : ℚ)) ≤ (Hex.bhksCutRadiusSq4 L : ℚ)) :
    Hex.bhksWithinGramSchmidtCut L dets i = true := by
  unfold Hex.bhksWithinGramSchmidtCut
  rw [if_neg hne]
  exact decide_eq_true hle

/-- A successful executable cut test exposes its determinant-ratio
inequality. -/
theorem bhksWithinGramSchmidtCut_le_of_eq_true
    (L : Hex.BhksLatticeBasis)
    (dets : Vector Nat (L.factorCount + L.coeffWidth + 1))
    (i : Fin (L.factorCount + L.coeffWidth))
    (hpass : Hex.bhksWithinGramSchmidtCut L dets i = true) :
    4 * ((dets.get ⟨i.val + 1, by omega⟩ : ℚ) /
        (dets.get ⟨i.val, by omega⟩ : ℚ)) ≤ (Hex.bhksCutRadiusSq4 L : ℚ) := by
  unfold Hex.bhksWithinGramSchmidtCut at hpass
  by_cases hzero : dets.get ⟨i.val, by omega⟩ = 0
  · simp [hzero] at hpass
  · rw [if_neg hzero] at hpass
    exact of_decide_eq_true hpass

/-- Every row in the retained prefix has a certified norm bound.  A retained
row need not itself pass the cut: the witness may be a later passing
Gram--Schmidt row.  The generic reduced-row estimate accounts for precisely
that prefix behavior. -/
theorem retainedRow_normSq_le
    (L : Hex.BhksLatticeBasis)
    (reduced : Hex.Matrix Int (L.factorCount + L.coeffWidth)
        (L.factorCount + L.coeffWidth))
    (hind : Hex.GramSchmidt.Int.independent reduced)
    (hred : Hex.isLLLReduced reduced (3 / 4) (1 / 2))
    (j : Fin (L.factorCount + L.coeffWidth))
    (hj : j.val < Hex.bhksCutPrefixCount L reduced) :
    4 * (((reduced.row j).normSq : Int) : Rat) ≤
      ((L.factorCount + L.coeffWidth : Nat) : Rat) *
        (2 : Rat) ^ (L.factorCount + L.coeffWidth - 1) *
          (Hex.bhksCutRadiusSq4 L : Rat) := by
  obtain ⟨k, hjk, hpass⟩ :=
    exists_passing_index_of_lt_prefixCount L reduced j hj
  have hrow := Hex.Internal.LLLCore.rowNormSq_le_basisNormSq reduced hred
    (by grind : (1 / 2 : Rat) * (1 / 2) ≤ 1)
    (by grind : (1 / 2 : Rat) * (1 / 2) < 3 / 4)
    (by grind : (3 / 4 : Rat) ≤ 1) j k hjk
  have halpha :
      (1 / ((3 / 4 : Rat) - (1 / 2 : Rat) * (1 / 2))) = 2 := by grind
  rw [halpha] at hrow
  set dets := Hex.GramSchmidt.Int.gramDetVec reduced with hdets
  have hd0 : dets.get ⟨k.val, by omega⟩ =
      Hex.GramSchmidt.Int.gramDet reduced k.val (Nat.le_of_lt k.isLt) :=
    Hex.GramSchmidt.Int.gramDetVec_eq_gramDet reduced
      (Hex.GramSchmidt.Int.StepWitness.ofGram reduced) k.val
      (Nat.le_of_lt k.isLt)
  have hd1 : dets.get ⟨k.val + 1, by omega⟩ =
      Hex.GramSchmidt.Int.gramDet reduced (k.val + 1) k.isLt :=
    Hex.GramSchmidt.Int.gramDetVec_eq_gramDet reduced
      (Hex.GramSchmidt.Int.StepWitness.ofGram reduced) (k.val + 1) k.isLt
  have hpass' : Hex.bhksWithinGramSchmidtCut L dets k = true := by
    simpa [dets] using hpass
  have hcut := bhksWithinGramSchmidtCut_le_of_eq_true L dets k hpass'
  rw [hd0, hd1] at hcut
  have hbnsq := Hex.GramSchmidt.Int.basis_normSq reduced hind k.val k.isLt
  rw [← hbnsq] at hcut
  let factor : Rat :=
    (L.factorCount + L.coeffWidth : Nat) *
      (2 : Rat) ^ (L.factorCount + L.coeffWidth - 1)
  have hfactor : 0 ≤ factor := by
    dsimp [factor]
    positivity
  have hfour := Rat.mul_le_mul_of_nonneg_left hrow (by grind : (0 : Rat) ≤ 4)
  have hscale := Rat.mul_le_mul_of_nonneg_left hcut hfactor
  calc
    4 * (((reduced.row j).normSq : Int) : Rat)
        ≤ 4 * (factor *
          Hex.Internal.LLLCore.basisNormSq (Hex.GramSchmidt.Int.basis reduced) k) := by
            simpa [factor] using hfour
    _ = factor * (4 *
          Hex.Internal.LLLCore.basisNormSq (Hex.GramSchmidt.Int.basis reduced) k) := by
            ring
    _ ≤ factor * (Hex.bhksCutRadiusSq4 L : Rat) := by
          simpa [Hex.Internal.LLLCore.basisNormSq] using hscale
    _ = ((L.factorCount + L.coeffWidth : Nat) : Rat) *
          (2 : Rat) ^ (L.factorCount + L.coeffWidth - 1) *
            (Hex.bhksCutRadiusSq4 L : Rat) := by rfl

/-- Executable-trace specialization of `retainedRow_normSq_le`: every source
row selected by `bhksProjectedRowsTrace` satisfies the retained-prefix norm
bound. -/
theorem traceRetainedRow_normSq_le
    (L : Hex.BhksLatticeBasis)
    (hrows : 1 ≤ L.factorCount + L.coeffWidth)
    (hind : Hex.GramSchmidt.Int.independent L.basis)
    (j : Fin (L.factorCount + L.coeffWidth))
    (hj : j.val < Hex.bhksCutPrefixCount L
      (Hex.bhksProjectedRowsTrace L hrows).reducedMatrix) :
    4 * ((((Hex.bhksProjectedRowsTrace L hrows).reducedMatrix.row j).normSq : Int) : Rat) ≤
      ((L.factorCount + L.coeffWidth : Nat) : Rat) *
        (2 : Rat) ^ (L.factorCount + L.coeffWidth - 1) *
          (Hex.bhksCutRadiusSq4 L : Rat) := by
  let reduced := (Hex.bhksProjectedRowsTrace L hrows).reducedMatrix
  have hreduced : reduced = Hex.lllNative L.basis (3 / 4)
      Hex.lll_delta_lower Hex.lll_delta_upper hrows := by
    exact Hex.bhksProjectedRowsTrace_reducedMatrix_eq L hrows
  have hind' : Hex.GramSchmidt.Int.independent reduced := by
    rw [hreduced]
    exact Hex.lllNative_independent L.basis (3 / 4)
      Hex.lll_delta_lower Hex.lll_delta_upper hrows hind
  have hred : Hex.isLLLReduced reduced (3 / 4) (1 / 2) := by
    rw [hreduced]
    exact Hex.lllNative_isLLLReduced L.basis (3 / 4)
      Hex.lll_delta_lower Hex.lll_delta_upper hrows hind
  exact retainedRow_normSq_le L reduced hind' hred j hj

/-- Every coordinate of a retained LLL row is bounded by a deliberately
coarse integral envelope for the retained-row norm estimate. -/
theorem traceRetainedRow_coord_natAbs_le
    (L : Hex.BhksLatticeBasis)
    (hrows : 1 ≤ L.factorCount + L.coeffWidth)
    (hind : Hex.GramSchmidt.Int.independent L.basis)
    (j : Fin (L.factorCount + L.coeffWidth))
    (hj : j.val < Hex.bhksCutPrefixCount L
      (Hex.bhksProjectedRowsTrace L hrows).reducedMatrix)
    (x : Fin (L.factorCount + L.coeffWidth)) :
    (((Hex.bhksProjectedRowsTrace L hrows).reducedMatrix.row j)[x]).natAbs ≤
      (L.factorCount + L.coeffWidth) *
        2 ^ (L.factorCount + L.coeffWidth) *
          Hex.bhksCutRadiusSq4 L := by
  let row := (Hex.bhksProjectedRowsTrace L hrows).reducedMatrix.row j
  let N := L.factorCount + L.coeffWidth
  let R := Hex.bhksCutRadiusSq4 L
  have hrat := traceRetainedRow_normSq_le L hrows hind j hj
  have hcoord_sq : row[x] ^ 2 ≤ Vector.normSq row := by
    unfold Vector.normSq Vector.dotProduct
    rw [finRange_foldl_add_eq_sum (g := fun i => row[i] * row[i])]
    rw [pow_two]
    exact Finset.single_le_sum (fun i _ => mul_self_nonneg row[i]) (Finset.mem_univ x)
  have hcoord_norm : (row[x].natAbs : ℤ) ≤ Vector.normSq row :=
    (Int.natAbs_le_self_sq row[x]).trans hcoord_sq
  have hcoord_rat :
      (row[x].natAbs : ℚ) ≤ ((Vector.normSq row : ℤ) : ℚ) := by
    change (((row[x].natAbs : Nat) : ℤ) : ℚ) ≤
      ((Vector.normSq row : ℤ) : ℚ)
    exact Int.cast_le.mpr hcoord_norm
  have hnorm_rat :
      ((Vector.normSq row : ℤ) : ℚ) ≤
        (N : ℚ) * 2 ^ (N - 1) * (R : ℚ) := by
    have hright : (0 : ℚ) ≤ (N : ℚ) * 2 ^ (N - 1) * (R : ℚ) := by positivity
    have hrat' :
        (4 : ℚ) * ((Vector.normSq row : ℤ) : ℚ) ≤
          (N : ℚ) * 2 ^ (N - 1) * (R : ℚ) := by
      simpa only [row, N, R] using hrat
    linarith
  have hpow : 2 ^ (N - 1) ≤ 2 ^ N :=
    Nat.pow_le_pow_right (by decide) (Nat.sub_le N 1)
  have hlarge :
      N * 2 ^ (N - 1) * R ≤ N * 2 ^ N * R := by
    gcongr
  have hlarge_rat :
      (N : ℚ) * 2 ^ (N - 1) * (R : ℚ) ≤
        ((N * 2 ^ N * R : Nat) : ℚ) := by
    exact_mod_cast hlarge
  exact_mod_cast hcoord_rat.trans (hnorm_rat.trans hlarge_rat)

/--
**BHKS prefix survivor-span (Lemma 5.7, forward).**

Any lattice vector `v` of the reduced BHKS basis whose squared length passes the
cut test (`4·‖v‖² ≤ bhksCutRadiusSq4`) lies in the integer span of the retained
prefix rows `b_0 … b_{t-1}`, where `t = bhksCutPrefixCount`.

The cut keeps a row `i` iff `4·‖b*_i‖² ≤ bhksCutRadiusSq4`, i.e.
`‖b*_i‖² ≤ bhksCutRadiusSq4 / 4`; the hypothesis is the matching tight bound on
`v` (four times its squared norm within the radius), *not* the loose
`‖v‖² ≤ bhksCutRadiusSq4`.
-/
theorem mem_prefixSubmodule_of_normSq_le
    (L : Hex.BhksLatticeBasis)
    (reduced : Hex.Matrix Int (L.factorCount + L.coeffWidth)
        (L.factorCount + L.coeffWidth))
    (hind : Hex.GramSchmidt.Int.independent reduced)
    (v : Vector Int (L.factorCount + L.coeffWidth))
    (hv : Hex.Matrix.memLattice reduced v)
    (hnorm : 4 * ((Vector.normSq v : Int) : ℚ) ≤ (Hex.bhksCutRadiusSq4 L : ℚ)) :
    HexMatrixMathlib.vectorEquiv v ∈
      HexLLLMathlib.prefixSubmodule reduced (Hex.bhksCutPrefixCount L reduced) := by
  by_cases hv0 : v = 0
  · subst hv0
    have hz : HexMatrixMathlib.vectorEquiv (0 : Vector Int (L.factorCount + L.coeffWidth))
        = (0 : Fin (L.factorCount + L.coeffWidth) → ℤ) := by
      funext i
      simp [HexMatrixMathlib.vectorEquiv]
    rw [hz]
    exact Submodule.zero_mem _
  · obtain ⟨k, c, hcv, hck, hzero_above, hbasis_norm⟩ :=
      Hex.GramSchmidt.Int.exists_top_index_normSq_le_of_memLattice reduced hind v hv hv0
    -- The top index `k` passes the cut test.
    set dets := Hex.GramSchmidt.Int.gramDetVec reduced with hdets
    have sw := Hex.GramSchmidt.Int.StepWitness.ofGram reduced
    have hd0 : dets.get ⟨k.val, by omega⟩
        = Hex.GramSchmidt.Int.gramDet reduced k.val (Nat.le_of_lt k.isLt) :=
      Hex.GramSchmidt.Int.gramDetVec_eq_gramDet reduced sw k.val (Nat.le_of_lt k.isLt)
    have hd1 : dets.get ⟨k.val + 1, by omega⟩
        = Hex.GramSchmidt.Int.gramDet reduced (k.val + 1) k.isLt :=
      Hex.GramSchmidt.Int.gramDetVec_eq_gramDet reduced sw (k.val + 1) k.isLt
    have hd0pos : 0 < Hex.GramSchmidt.Int.gramDet reduced k.val (Nat.le_of_lt k.isLt) := by
      rcases Nat.eq_zero_or_pos k.val with hk0 | hkpos
      · simp only [hk0]
        rw [Hex.GramSchmidt.Int.gramDet_zero]
        exact Nat.one_pos
      · exact Hex.GramSchmidt.Int.gramDet_pos reduced hind k.val (Nat.le_of_lt k.isLt) hkpos
    have hne : dets.get ⟨k.val, by omega⟩ ≠ 0 := by
      rw [hd0]; omega
    -- `‖b*_k‖² = gramDet(k+1)/gramDet(k)`.
    have hbnsq := Hex.GramSchmidt.Int.basis_normSq reduced hind k.val k.isLt
    have hpass : Hex.bhksWithinGramSchmidtCut L dets k = true := by
      refine bhksWithinGramSchmidtCut_eq_true_of_le L dets k hne ?_
      rw [hd0, hd1]
      -- goal: 4 * (gramDet(k+1)/gramDet(k)) ≤ radius
      rw [← hbnsq]
      -- goal: 4 * ‖b*_k‖² ≤ radius, with ‖b*_k‖² ≤ ‖v‖²
      calc 4 * Vector.normSq ((Hex.GramSchmidt.Int.basis reduced).row ⟨k.val, k.isLt⟩)
          ≤ 4 * ((Vector.normSq v : Int) : ℚ) := by
            have := hbasis_norm
            nlinarith [hbasis_norm]
        _ ≤ (Hex.bhksCutRadiusSq4 L : ℚ) := hnorm
    have hklt : k.val < Hex.bhksCutPrefixCount L reduced :=
      bhksWithinGramSchmidtCut_lt_prefixCount L reduced k (by rw [← hdets]; exact hpass)
    -- `c` vanishes at and above the retained prefix length.
    have hc : ∀ i : Fin (L.factorCount + L.coeffWidth),
        Hex.bhksCutPrefixCount L reduced ≤ i.val → c[i] = 0 := by
      intro i hi
      exact hzero_above i (by omega)
    have := HexLLLMathlib.vecMul_mem_prefixSubmodule_of_vector
      reduced c (Hex.bhksCutPrefixCount L reduced) hc
    rwa [hcv] at this

/--
Cut hypotheses needed to connect the executable projected rows to the abstract
true-factor supports.  Later B4/B5 work discharges `indicator_mem_projected`
from the BHKS norm bound and Gram-Schmidt cut soundness.
-/
structure CutProjectionHypotheses
    (L : Hex.BhksProjectedRows) (trueSupports : Set (Set (Fin L.factorCount))) where
  /-- Every genuine support indicator belongs to the span of the projected rows. -/
  indicator_mem_projected :
    ∀ S : trueSupports, indicatorVector S.1 ∈ projectedRowSpanInt L

/-- Direct caller-facing form of the cut hypothesis for one true support. -/
theorem indicatorVector_mem_projectedRowSpan_of_cut
    (L : Hex.BhksProjectedRows) (trueSupports : Set (Set (Fin L.factorCount)))
    (hcut : CutProjectionHypotheses L trueSupports) (S : trueSupports) :
    indicatorVector S.1 ∈ projectedRowSpanInt L :=
  hcut.indicator_mem_projected S

/-- The existing per-support cut theorem is exactly the forward lattice
containment `W ≤ L'`. -/
theorem trueSupportSpanInt_le_projectedRowSpanInt
    (L : Hex.BhksProjectedRows)
    (trueSupports : Set (Set (Fin L.factorCount)))
    (hcut : CutProjectionHypotheses L trueSupports) :
    trueSupportSpanInt trueSupports ≤ projectedRowSpanInt L := by
  apply Submodule.span_le.mpr
  rintro _ ⟨S, rfl⟩
  exact hcut.indicator_mem_projected S

/-- Reverse containment reduces to checking the retained projected generators.
This is the proof-facing endpoint of the bad-vector contradiction: once every
retained projected row is in `W`, its whole integer span is in `W`. -/
theorem projectedRowSpanInt_le_trueSupportSpanInt_of_rows
    (L : Hex.BhksProjectedRows)
    (trueSupports : Set (Set (Fin L.factorCount)))
    (hrows : ∀ i : Fin L.projectedRows.size,
      Matrix.row (projectedRowsIntMatrix L) i ∈ trueSupportSpanInt trueSupports) :
    projectedRowSpanInt L ≤ trueSupportSpanInt trueSupports := by
  apply Submodule.span_le.mpr
  rintro _ ⟨i, rfl⟩
  exact hrows i

/-- Equality form of the two BHKS containments. -/
theorem projectedRowSpanInt_eq_trueSupportSpanInt
    (L : Hex.BhksProjectedRows)
    (trueSupports : Set (Set (Fin L.factorCount)))
    (hcut : CutProjectionHypotheses L trueSupports)
    (hrows : ∀ i : Fin L.projectedRows.size,
      Matrix.row (projectedRowsIntMatrix L) i ∈ trueSupportSpanInt trueSupports) :
    projectedRowSpanInt L = trueSupportSpanInt trueSupports := by
  apply le_antisymm
  · exact projectedRowSpanInt_le_trueSupportSpanInt_of_rows L trueSupports hrows
  · exact trueSupportSpanInt_le_projectedRowSpanInt L trueSupports hcut

/-- Every projected matrix row belongs to the integer span of the projected rows. -/
theorem projectedRow_mem_projectedRowSpanInt
    (L : Hex.BhksProjectedRows) (i : Fin L.projectedRows.size) :
    Matrix.row (projectedRowsIntMatrix L) i ∈ projectedRowSpanInt L := by
  exact Submodule.subset_span ⟨i, rfl⟩
end BHKS

end

end HexBerlekampZassenhausMathlib
